[versions]
minecraft = "1.21"
fabric_mappings = "1.21+build.2"
fabric_loader = "0.15.11"
fabric_api = "0.100.1+1.21"
modmenu = "9.0.0"
yacl = "3.5.0+1.21-fabric"

paper_api = "1.20.6-R0.1-SNAPSHOT"
netty_buffer = "4.1.111.Final"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_mappings = { module = "net.fabricmc:yarn", version.ref = "fabric_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }

paper_api = { module = "io.papermc.paper:paper-api", version.ref = "paper_api" }
netty_buffer = { module = "io.netty:netty-buffer", version.ref = "netty_buffer" }

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.6.12" }
