name: Streamotes
version: '${version}'
main: xeed.mc.paper.streamotes.Streamotes
api-version: '1.20'
folia-supported: true
authors: [ Xspeed ]
commands:
  streamotes:
    description: Streamotes configuration management
    usage: /<command> [reload]
    aliases: [ streamotes ]
permissions:
  xeed.mc.streamotes:
    description: Streamotes configuration access
    default: false
